/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#c7c4d7",
        "secondary-fixed": "#eedcff",
        "on-primary-fixed-variant": "#332dbc",
        "surface": "#0f131d",
        "tertiary": "#adc6ff",
        "surface-container": "#1c1f2a",
        "surface-tint": "#c2c1ff",
        "outline": "#918fa0",
        "secondary-fixed-dim": "#d8b9ff",
        "primary-fixed": "#e2dfff",
        "surface-bright": "#353944",
        "inverse-surface": "#dfe2f1",
        "inverse-primary": "#4d4ad5",
        "background": "#0f131d",
        "on-error": "#690005",
        "on-secondary-container": "#d0acff",
        "error": "#ffb4ab",
        "surface-container-lowest": "#0a0e18",
        "surface-container-high": "#262a35",
        "inverse-on-surface": "#2c303b",
        "on-primary-container": "#f4f1ff",
        "on-error-container": "#ffdad6",
        "surface-variant": "#313540",
        "on-tertiary-fixed-variant": "#004493",
        "on-tertiary": "#002e69",
        "on-primary": "#1800a7",
        "primary": "#c2c1ff",
        "on-secondary-fixed-variant": "#6300bb",
        "surface-container-highest": "#313540",
        "surface-container-low": "#171b26",
        "error-container": "#93000a",
        "on-secondary-fixed": "#290055",
        "on-tertiary-fixed": "#001a41",
        "secondary-container": "#6904c5",
        "on-tertiary-container": "#eff2ff",
        "on-secondary": "#450086",
        "surface-dim": "#0f131d",
        "primary-fixed-dim": "#c2c1ff",
        "primary-container": "#5e5ce6",
        "outline-variant": "#464554",
        "on-surface": "#dfe2f1",
        "tertiary-fixed": "#d8e2ff",
        "secondary": "#d8b9ff",
        "tertiary-container": "#006adf",
        "tertiary-fixed-dim": "#adc6ff",
        "on-background": "#dfe2f1",
        "on-primary-fixed": "#0c006b"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "container-max": "1440px",
        "unit": "8px",
        "section-gap": "80px",
        "margin-desktop": "64px",
        "gutter": "24px"
      },
      fontFamily: {
        "display-lg": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "code-preview": ["Geist"],
        "body-md": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "display-lg-mobile": ["Hanken Grotesk"],
        "label-caps": ["Geist"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "code-preview": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
